# Generated by Django 3.2.3 on 2021-05-29 20:51

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=builtins.max, verbose_name='Description')),
                ('likeNum', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
