# Generated by Django 3.2.3 on 2021-05-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likers',
            new_name='likedBy',
        ),
    ]
