# Generated by Django 3.2.3 on 2021-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_likers_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.AddField(
            model_name='post',
            name='posterid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
