# Generated by Django 3.2.3 on 2021-05-30 12:01

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210530_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedBy',
            field=models.TextField(default='[]', max_length=builtins.max),
        ),
    ]
